// Package internal_docs Code generated by swaggo/swag. DO NOT EDIT
package internal_docs

import "github.com/swaggo/swag"

const docTemplateinternal = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/appointments": {
            "get": {
                "description": "Retrieves a list of all appointments.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointments"
                ],
                "summary": "Get all appointments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by start date",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by end date",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Schedules a new appointment for a student.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointments"
                ],
                "summary": "Book a new appointment",
                "parameters": [
                    {
                        "description": "Appointment Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appointments.AppointmentDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/appointments/calendar/stats": {
            "get": {
                "description": "Retrieves appointment status counts by date.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointments"
                ],
                "summary": "Get daily status count",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/appointments.DailyStatusCount"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/appointments/id/{id}": {
            "get": {
                "description": "Retrieves the details of a specific appointment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointments"
                ],
                "summary": "Get appointment details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Appointment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/appointments.Appointment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/appointments/lookups/categories": {
            "get": {
                "description": "Retrieves available appointment categories.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointments"
                ],
                "summary": "Get appointment categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/appointments.AppointmentCategory"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/appointments/lookups/slots": {
            "get": {
                "description": "Retrieves available time slots for a date.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointments"
                ],
                "summary": "Get available time slots",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/appointments.AvailableTimeSlotView"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/appointments/lookups/statuses": {
            "get": {
                "description": "Retrieves available appointment statuses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointments"
                ],
                "summary": "Get appointment statuses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/appointments.AppointmentStatus"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/appointments/me": {
            "get": {
                "description": "Retrieves appointments for the authenticated student.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointments"
                ],
                "summary": "Get student's appointments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/appointments/stats": {
            "get": {
                "description": "Retrieves appointment status counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointments"
                ],
                "summary": "Get appointment statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/appointments.StatusCount"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/integrations/students/profile": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get student information by their email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "External Students"
                ],
                "summary": "Get student by Email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student Email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.StudentSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/integrations/students/profiles": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a paginated list of students with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "External Students"
                ],
                "summary": "List students",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term for student name or number",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by program ID",
                        "name": "program_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by gender ID",
                        "name": "gender_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by year level",
                        "name": "year_level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order by field",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page for pagination",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.ListStudentsSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/integrations/students/{studentNumber}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get student information by student number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "External Students"
                ],
                "summary": "Get student by student number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student number of the student",
                        "name": "studentNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.StudentSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/integrations/students/{studentNumber}/addresses": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all addresses of a student by their student number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "External Students"
                ],
                "summary": "Get student addresses by student number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student number of the student",
                        "name": "studentNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.StudentAddressSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/integrations/students/{studentNumber}/personal-info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get personal information of a student by their student number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "External Students"
                ],
                "summary": "Get personal information by student number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student number of the student",
                        "name": "studentNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.StudentPersonalInfoSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/slips": {
            "get": {
                "description": "Retrieves list of all submitted slips.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Get all excuse slips",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Allows a student to submit an excuse slip with\nsupporting document (file upload).",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Submit an excuse slip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Reason for absence",
                        "name": "reason",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "absenceDate",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Supporting Document",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slips/id/{id}": {
            "get": {
                "description": "Retrieves details for a specific excuse slip.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Get excuse slip by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/slips.SlipDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slips/id/{id}/attachments": {
            "get": {
                "description": "Retrieves attachments for a specific slip.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Get slip attachments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Slip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/slips.AttachmentDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slips/id/{id}/attachments/{attachmentId}": {
            "get": {
                "description": "Downloads a specific attachment file.",
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Download attachment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Attachment ID",
                        "name": "attachmentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slips/id/{id}/status": {
            "patch": {
                "description": "Approve, reject, or request revision of slip.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Update slip status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Slip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status and notes",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/slips.UpdateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slips/lookups/categories": {
            "get": {
                "description": "Retrieves available slip categories.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Get slip categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/slips.SlipCategory"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slips/lookups/statuses": {
            "get": {
                "description": "Retrieves available slip statuses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Get slip statuses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/slips.SlipStatus"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slips/me": {
            "get": {
                "description": "Retrieves slips for the authenticated student.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Get student's excuse slips",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slips/stats": {
            "get": {
                "description": "Retrieves slip status counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Get slip statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/slips.SlipStatusCount"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slips/tickets/claim": {
            "post": {
                "description": "Allows a counselor to verify a student's ticket on-site.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Claim/Verify a ticket",
                "parameters": [
                    {
                        "description": "Ticket code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/slips.TicketClaimRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slips/tickets/{code}": {
            "get": {
                "description": "Allows a counselor to view slip details before verification.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Get slip details by ticket code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticket code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/slips.Slip"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slips/urgent": {
            "get": {
                "description": "Retrieves urgent slips for counselor review.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExcuseSlips"
                ],
                "summary": "Get urgent excuse slips",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/students": {
            "get": {
                "description": "Retrieves a paginated list of students with optional filters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "List Students",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by program ID",
                        "name": "program_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by year level",
                        "name": "year_level",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by gender ID",
                        "name": "gender_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of records per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/students.ListStudentsResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list students",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/students/{iirID}/iir/download": {
            "get": {
                "description": "Generates and downloads the student's Initial Interview Record",
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Generate Student IIR PDF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IIR ID",
                        "name": "iirID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "appointments.Appointment": {
            "type": "object",
            "properties": {
                "adminNotes": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "appointmentCategoryId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "iirId": {
                    "type": "string"
                },
                "prefDate1": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "prefDate2": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "prefDate3": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "prefTimeSlotID1": {
                    "$ref": "#/definitions/structs.NullableInt64"
                },
                "prefTimeSlotID2": {
                    "$ref": "#/definitions/structs.NullableInt64"
                },
                "prefTimeSlotID3": {
                    "$ref": "#/definitions/structs.NullableInt64"
                },
                "reason": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "statusId": {
                    "type": "integer"
                },
                "timeSlotId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "urgencyLevel": {
                    "type": "string"
                },
                "urgencyScore": {
                    "type": "number"
                },
                "whenDate": {
                    "type": "string"
                }
            }
        },
        "appointments.AppointmentCategory": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "appointments.AppointmentDTO": {
            "type": "object",
            "properties": {
                "adminNotes": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "appointmentCategory": {
                    "$ref": "#/definitions/appointments.AppointmentCategory"
                },
                "createdAt": {
                    "type": "string"
                },
                "hasSignificantNote": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "iirId": {
                    "type": "string"
                },
                "preferredDate1": {
                    "type": "string"
                },
                "preferredDate2": {
                    "type": "string"
                },
                "preferredDate3": {
                    "type": "string"
                },
                "preferredTimeSlot1": {
                    "$ref": "#/definitions/appointments.TimeSlot"
                },
                "preferredTimeSlot2": {
                    "$ref": "#/definitions/appointments.TimeSlot"
                },
                "preferredTimeSlot3": {
                    "$ref": "#/definitions/appointments.TimeSlot"
                },
                "reason": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "status": {
                    "$ref": "#/definitions/appointments.AppointmentStatus"
                },
                "studentCorUrl": {
                    "type": "string"
                },
                "studentNumber": {
                    "type": "string"
                },
                "timeSlot": {
                    "$ref": "#/definitions/appointments.TimeSlot"
                },
                "updatedAt": {
                    "type": "string"
                },
                "urgencyLevel": {
                    "type": "string"
                },
                "urgencyScore": {
                    "type": "number"
                },
                "user": {
                    "$ref": "#/definitions/users.UserResponse"
                },
                "userId": {
                    "type": "string"
                },
                "whenDate": {
                    "type": "string"
                }
            }
        },
        "appointments.AppointmentStatus": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "appointments.AvailableTimeSlotView": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isAvailable": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "appointments.DailyStatusCount": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "pendingCount": {
                    "type": "integer"
                },
                "rescheduledCount": {
                    "type": "integer"
                },
                "scheduledCount": {
                    "type": "integer"
                }
            }
        },
        "appointments.StatusCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "appointments.TimeSlot": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "integrations.ListStudentsSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/integrations.OGOSListStudentsResponse"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.JSendStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "integrations.OGOSListStudentsResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/structs.PaginationMetadata"
                },
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/integrations.OGOSStudentDTO"
                    }
                }
            }
        },
        "integrations.OGOSStudentAddressDTO": {
            "type": "object",
            "properties": {
                "addressType": {
                    "type": "string"
                },
                "barangay": {
                    "$ref": "#/definitions/locations.Barangay"
                },
                "city": {
                    "$ref": "#/definitions/locations.City"
                },
                "province": {
                    "$ref": "#/definitions/locations.ProvinceDTO"
                },
                "region": {
                    "$ref": "#/definitions/locations.Region"
                },
                "streetDetail": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "studentNumber": {
                    "type": "string"
                }
            }
        },
        "integrations.OGOSStudentDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "mobileNumber": {
                    "type": "string"
                },
                "program": {
                    "$ref": "#/definitions/students.Program"
                },
                "section": {
                    "type": "string"
                },
                "studentNumber": {
                    "type": "string"
                },
                "suffixName": {
                    "type": "string"
                },
                "yearLevel": {
                    "type": "integer"
                }
            }
        },
        "integrations.OGOSStudentPersonalInfoDTO": {
            "type": "object",
            "properties": {
                "dateOfBirth": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/students.Gender"
                },
                "heightM": {
                    "type": "number"
                },
                "placeOfBirth": {
                    "type": "string"
                },
                "studentNumber": {
                    "type": "string"
                },
                "weightKg": {
                    "type": "number"
                }
            }
        },
        "integrations.StudentAddressSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/integrations.OGOSStudentAddressDTO"
                    }
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.JSendStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "integrations.StudentPersonalInfoSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/integrations.OGOSStudentPersonalInfoDTO"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.JSendStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "integrations.StudentSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/integrations.OGOSStudentDTO"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "locations.Barangay": {
            "type": "object",
            "properties": {
                "cityCode": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "locations.City": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "district": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "provinceCode": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "regionCode": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "type": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "zipCode": {
                    "$ref": "#/definitions/structs.NullableString"
                }
            }
        },
        "locations.ProvinceDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "regionCode": {
                    "$ref": "#/definitions/structs.NullableString"
                }
            }
        },
        "locations.Region": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "response.CommonErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Detailed error message"
                },
                "status": {
                    "type": "string",
                    "example": "fail"
                }
            }
        },
        "response.JSendStatus": {
            "type": "string",
            "enum": [
                "success",
                "fail",
                "error"
            ],
            "x-enum-varnames": [
                "StatusSuccess",
                "StatusFail",
                "StatusError"
            ]
        },
        "slips.AttachmentDTO": {
            "type": "object",
            "properties": {
                "attachmentType": {
                    "type": "string"
                },
                "fileName": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "fileType": {
                    "type": "string"
                },
                "fileUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                },
                "slipId": {
                    "type": "string"
                }
            }
        },
        "slips.Slip": {
            "type": "object",
            "properties": {
                "adminNotes": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "categoryId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "dateNeeded": {
                    "type": "string"
                },
                "dateOfAbsence": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "iirId": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "statusId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "slips.SlipCategory": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "slips.SlipDTO": {
            "type": "object",
            "properties": {
                "adminNotes": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "category": {
                    "$ref": "#/definitions/slips.SlipCategory"
                },
                "createdAt": {
                    "type": "string"
                },
                "dateNeeded": {
                    "type": "string"
                },
                "dateOfAbsence": {
                    "type": "string"
                },
                "hasSignificantNote": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "iirId": {
                    "type": "string"
                },
                "isVerified": {
                    "type": "boolean"
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/slips.SlipStatus"
                },
                "studentCorUrl": {
                    "type": "string"
                },
                "studentNumber": {
                    "type": "string"
                },
                "ticket": {
                    "$ref": "#/definitions/slips.TicketDTO"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/users.UserResponse"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "slips.SlipStatus": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "slips.SlipStatusCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "slips.TicketClaimRequest": {
            "type": "object",
            "required": [
                "ticketCode"
            ],
            "properties": {
                "ticketCode": {
                    "type": "string"
                }
            }
        },
        "slips.TicketDTO": {
            "type": "object",
            "properties": {
                "isVerified": {
                    "type": "boolean"
                },
                "ticketCode": {
                    "type": "string"
                },
                "verifiedAt": {
                    "type": "string"
                }
            }
        },
        "slips.UpdateStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "adminNotes": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "structs.NullableInt64": {
            "type": "object",
            "properties": {
                "int64": {
                    "type": "integer",
                    "format": "int64"
                },
                "valid": {
                    "description": "Valid is true if Int64 is not NULL",
                    "type": "boolean"
                }
            }
        },
        "structs.NullableString": {
            "type": "object",
            "properties": {
                "string": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if String is not NULL",
                    "type": "boolean"
                }
            }
        },
        "structs.PaginationMetadata": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pagesSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "students.Gender": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "students.ListStudentsResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/structs.PaginationMetadata"
                },
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/students.StudentProfileDTO"
                    }
                }
            }
        },
        "students.Program": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "students.StudentProfileDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/students.Gender"
                },
                "iirId": {
                    "type": "string"
                },
                "isStudentCorValid": {
                    "type": "boolean"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "profilePicture": {
                    "type": "string"
                },
                "program": {
                    "$ref": "#/definitions/students.Program"
                },
                "section": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/students.StudentStatus"
                },
                "studentCorUrl": {
                    "type": "string"
                },
                "studentNumber": {
                    "type": "string"
                },
                "suffixName": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "userId": {
                    "type": "string"
                },
                "yearLevel": {
                    "type": "integer"
                }
            }
        },
        "students.StudentStatus": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "users.Role": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "users.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "profilePicture": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/users.Role"
                    }
                },
                "suffixName": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfointernal holds exported Swagger Info so clients can modify it
var SwaggerInfointernal = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Student data API",
	Description:      "",
	InfoInstanceName: "internal",
	SwaggerTemplate:  docTemplateinternal,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfointernal.InstanceName(), SwaggerInfointernal)
}
