name: Deploy

on:
    push:
        branches: [main, staging]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: ${{github.ref_name == 'main' && 'prod' || 'staging'}}
        steps:
            - name: Deploy to Hostinger via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST}}
                  username: ${{ secrets.SSH_USERNAME}}
                  key: ${{ secrets.SSH_KEY}}
                  port: ${{ secrets.SSH_PORT}}
                  script: |
                      REF="${{ github.ref_name }}"
                      ENV_NAME="staging"
                      if [ "$REF" = "main" ]; then
                        ENV_NAME="prod"
                      fi
                      cd "/home/docker/projects/capstone-${ENV_NAME}"
                      echo "${{ secrets.GITHUB_TOKEN }}" | \
                        docker login ghcr.io \
                        -u ${{ github.repository_owner }} \
                        --password-stdin
                      docker compose pull
                      docker compose up -d
